import intf_libs += libdatatree%lib{datatree}
import intf_libs += libcrails-semantics%lib{crails-semantics}
import intf_libs += libcrails-controllers%lib{crails-controllers}

lib{crails-i18n}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_I18N_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_I18N_SHARED_BUILD

# Export options.
#
lib{crails-i18n}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{crails-i18n}: cxx.export.poptions += -DLIBCRAILS_I18N_STATIC
libs{crails-i18n}: cxx.export.poptions += -DLIBCRAILS_I18N_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{crails-i18n}: bin.lib.version = "-$version.project_id"
else
  lib{crails-i18n}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libcrails-i18n/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
